"""Static full-model MMLU acceptance with explicit clocks and bounded stopping."""
from __future__ import annotations

import copy
import hashlib
import json
import random
import time
from pathlib import Path

import numpy as np
import torch
import torch.distributed as dist
from transformers import AutoModelForCausalLM
from transformers.modeling_utils import no_init_weights


def model_state_digest(model, dtype=torch.float16):
    """Hash all named weights, including tied aliases, in a declared comparison dtype."""
    digest = hashlib.sha256()
    for name, value in model.state_dict().items():
        tensor = value.detach().cpu()
        if tensor.is_floating_point():
            tensor = tensor.to(dtype)
        tensor = tensor.contiguous()
        digest.update(name.encode() + b"\0")
        digest.update(str(tuple(tensor.shape)).encode() + b"\0")
        digest.update(str(tensor.dtype).encode() + b"\0")
        # uint8 also supports tensors whose dtype NumPy does not expose.
        digest.update(tensor.reshape(-1).view(torch.uint8).numpy().tobytes())
    return digest.hexdigest()


def stop_reason(successful_steps, elapsed_seconds, *, max_steps=0, max_seconds=0):
    if max_steps and successful_steps >= max_steps:
        return "successful_step_limit"
    if max_seconds and elapsed_seconds >= max_seconds:
        return "wall_time_limit"
    return None


class MathAcceptance:
    def __init__(self, args, tokenizer, initial_digest, plan, initialization_started):
        from .mmlu_math import load_mmlu_math

        self.args, self.tokenizer = args, tokenizer
        self.rank = dist.get_rank()
        self.initial_digest = initial_digest
        self.plan = plan
        self.initialization_started = initialization_started
        self.directory = Path(args.helix_acceptance_dir)
        local_error = None
        self.data = None
        try:
            self.directory.mkdir(parents=True, exist_ok=True)
            if (self.directory / "evaluations.jsonl").exists():
                raise FileExistsError("Choose a fresh acceptance directory")
            loaded_data = load_mmlu_math(args.helix_mmlu_path)
            if self.rank == 0:
                self.data = loaded_data
        except Exception as error:
            local_error = f"rank {self.rank}: {type(error).__name__}: {error}"
        errors = [None] * dist.get_world_size()
        dist.all_gather_object(errors, local_error)
        if any(error is not None for error in errors):
            raise RuntimeError("Acceptance preflight failed: " + "; ".join(str(error) for error in errors if error))
        self.eval_model = None
        self.training_started = None
        self.successful_steps = self.attempts = self.samples = 0
        self.successful_samples = 0
        self.training_seconds = 0.0
        self.last_evaluated_attempt = -1
        self.evaluations = []
        self.target = None
        self.protocol_hash = None
        self.best_accuracy = -1.0
        self.finished = False

    def _elapsed(self):
        return 0.0 if self.training_started is None else time.perf_counter() - self.training_started

    def _evaluate_on_root(self, engine):
        from .mmlu_math import evaluate_mmlu_math

        py_state, np_state = random.getstate(), np.random.get_state()
        device = torch.device(engine.device)
        with torch.random.fork_rng(devices=[device.index]):
            try:
                if self.eval_model is None:
                    config = copy.deepcopy(engine.full_model.config)
                    config.use_cache = False
                    with no_init_weights():
                        self.eval_model = AutoModelForCausalLM.from_config(
                            config, torch_dtype=torch.float16, attn_implementation="sdpa"
                        )
                    # no_init_weights skips the usual post-init alias setup.
                    self.eval_model.tie_weights()
                    self.eval_model.requires_grad_(False)
                self.eval_model.load_state_dict(engine.full_model.state_dict(), strict=True)
                # Parameters were created in FP16 above. Device-only movement
                # preserves FP32 RoPE frequencies, which are nonpersistent
                # buffers and are regenerated by save/reload.
                self.eval_model.to(device=device).eval()
                return evaluate_mmlu_math(
                    self.eval_model, self.tokenizer, self.data,
                    device=device, batch_size=self.args.helix_eval_batch_size,
                    max_length=self.args.helix_eval_max_length,
                    num_fewshot=self.args.helix_eval_fewshot,
                    overflow_policy="error",
                )
            finally:
                if self.eval_model is not None:
                    self.eval_model.to("cpu")
                random.setstate(py_state)
                np.random.set_state(np_state)
                torch.cuda.empty_cache()

    def evaluate(self, engine, *, reason):
        started = time.perf_counter()
        engine.gather_full_model()
        gather_seconds = time.perf_counter() - started
        payload = [None]
        if self.rank == 0:
            try:
                digest = model_state_digest(engine.full_model)
                if self.attempts == 0 and digest != self.initial_digest:
                    raise RuntimeError("Initial NCCL reconstruction differs from canonical FP16 checkpoint")
                eval_started = time.perf_counter()
                result = self._evaluate_on_root(engine)
                accuracy = float(result["accuracy"])
                if not 0.0 <= accuracy <= 1.0:
                    raise ValueError("Evaluator accuracy must be a fraction in [0, 1]")
                questions = int(result["num_questions"])
                correct = int(result["num_correct"])
                if questions != len(self.data.test) or not 0 <= correct <= questions:
                    raise ValueError("Evaluation must cover the complete fixed test set")
                if abs(accuracy - correct / questions) > 1e-12:
                    raise ValueError("Evaluator score disagrees with exact question counts")
                if self.protocol_hash is not None and self.protocol_hash != result["protocol_hash"]:
                    raise ValueError("Evaluation protocol changed during the run")
                self.protocol_hash = result["protocol_hash"]
                elapsed = self._elapsed()
                record = {
                    **result, "attempted_steps": self.attempts,
                    "successful_steps": self.successful_steps,
                    "samples_seen": self.samples,
                    "samples_in_successful_updates": self.successful_samples,
                    "reason": reason, "model_state_sha256_fp16": digest,
                    "initial_reconstruction_verified": self.attempts == 0,
                    "gather_seconds": gather_seconds,
                    "evaluation_seconds": time.perf_counter() - eval_started,
                    "training_elapsed_seconds": elapsed,
                    "measured_training_step_seconds": self.training_seconds,
                    "since_initialization_seconds": time.perf_counter() - self.initialization_started,
                    "observed_at_unix": time.time(),
                }
                path = self.directory / f"eval_attempt_{self.attempts:07d}.json"
                path.write_text(json.dumps(record, indent=2, allow_nan=False) + "\n")
                compact = {key: value for key, value in record.items() if key != "predictions"}
                with (self.directory / "evaluations.jsonl").open("a") as stream:
                    stream.write(json.dumps(compact, allow_nan=False) + "\n")
                improved = accuracy > self.best_accuracy
                self.best_accuracy = max(self.best_accuracy, accuracy)
                if accuracy >= self.args.helix_target_accuracy and self.target is None:
                    self.target = {
                        "accuracy": accuracy, "successful_steps": self.successful_steps,
                        "attempted_steps": self.attempts,
                        "time_to_target_seconds": elapsed,
                        "initial_model_already_met_target": self.attempts == 0,
                        "protocol_hash": result["protocol_hash"],
                    }
                self.evaluations.append(compact)
                self.last_evaluated_attempt = self.attempts
                payload[0] = {"accuracy": accuracy, "target": self.target, "improved": improved}
                print(f"MMLU-math full-model eval: success_steps={self.successful_steps} "
                      f"accuracy={accuracy:.6f} elapsed={elapsed:.2f}s reason={reason}", flush=True)
            except Exception as error:
                payload[0] = {"error": f"{type(error).__name__}: {error}"}
        dist.broadcast_object_list(payload, src=0)
        if "error" in payload[0]:
            raise RuntimeError("Full-model acceptance evaluation failed: " + payload[0]["error"])
        self.target = payload[0]["target"]
        self.last_evaluated_attempt = self.attempts
        return self.target is not None

    def begin(self, engine):
        reached = self.evaluate(engine, reason="initial_reconstruction")
        dist.barrier()
        if not reached:
            self.training_started = time.perf_counter()
        return reached

    def after_step(self, engine, *, applied, step_seconds, global_batch):
        self.attempts += 1
        self.samples += global_batch
        self.successful_steps += int(applied)
        self.successful_samples += global_batch * int(applied)
        self.training_seconds += step_seconds
        decision = [None]
        if self.rank == 0:
            reason = stop_reason(
                self.successful_steps, self._elapsed(),
                max_steps=self.args.helix_max_successful_steps,
                max_seconds=self.args.helix_max_train_seconds,
            )
            periodic = applied and self.successful_steps % self.args.helix_eval_interval == 0
            decision[0] = {"stop_reason": reason, "evaluate": bool(reason or periodic)}
        dist.broadcast_object_list(decision, src=0)
        if decision[0]["evaluate"]:
            reached = self.evaluate(engine, reason=decision[0]["stop_reason"] or "periodic")
            if reached:
                return "target_reached"
        return decision[0]["stop_reason"]

    def finish(self, engine, reason):
        if self.finished:
            return
        if self.last_evaluated_attempt != self.attempts:
            self.evaluate(engine, reason="final_" + reason)
        if self.target is not None:
            reason = "target_reached"
        payload = [None]
        if self.rank == 0:
            try:
                checkpoint = self.directory / ("target_model" if self.target else "final_model")
                checkpoint.mkdir(parents=True, exist_ok=False)
                self.eval_model.save_pretrained(checkpoint, safe_serialization=True, max_shard_size="2GB")
                self.tokenizer.save_pretrained(checkpoint)
                summary = {
                    "status": "target_reached" if self.target else "target_not_reached",
                    "stop_reason": reason, "target_accuracy": self.args.helix_target_accuracy,
                    "best_accuracy": self.best_accuracy, "target": self.target,
                    "final_accuracy": self.evaluations[-1]["accuracy"],
                    "protocol_hash": self.protocol_hash,
                    "checkpoint_state_sha256_fp16": self.evaluations[-1]["model_state_sha256_fp16"],
                    "attempted_steps": self.attempts, "successful_steps": self.successful_steps,
                    "overflow_steps": self.attempts - self.successful_steps,
                    "samples_seen": self.samples, "successful_samples": self.successful_samples,
                    "training_wall_seconds": self._elapsed(),
                    "since_initialization_seconds": time.perf_counter() - self.initialization_started,
                    "measured_training_step_seconds": self.training_seconds,
                    "checkpoint": str(checkpoint), "checkpoint_kind": "full_reconstructed_model_weights_only",
                    "evaluation_history": self.evaluations,
                    "time_definition": "First observed target evaluation; training wall clock starts after initial evaluation and includes periodic gather/eval. Offline profile/search and initialization are separate. Initial success has time-to-target zero.",
                    "budget_definition": "Train wall limit checked between updates; final full evaluation and checkpoint are allowed to complete after the limit.",
                }
                (self.directory / "acceptance_summary.json").write_text(json.dumps(summary, indent=2, allow_nan=False) + "\n")
                payload[0] = {"ok": True}
            except Exception as error:
                payload[0] = {"error": f"{type(error).__name__}: {error}"}
        dist.broadcast_object_list(payload, src=0)
        if "error" in payload[0]:
            raise RuntimeError("Acceptance checkpoint failed: " + payload[0]["error"])
        self.finished = True
